name: CI-CD
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1.9.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            fabricioveronez/rotten-potatoes:latest
            fabricioveronez/rotten-potatoes:${{github.run_number}}
            
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v2
  
      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.K8S_CONFIG}}
          
      - name: Deploy Aplicação
        uses: Azure/k8s-deploy@v1.3
        with:
          images: fabricioveronez/rotten-potatoes:${{github.run_number}}
          manifests: |
            k8s/deployment.yaml
